"use strict";

/*
 * Catálogo de comidas do WarSpawn
 *
 * Este arquivo contém apenas dados. A interface é construída por food-system.js.
 * Para adicionar um item novo, basta incluir uma entrada em `items`; receitas usam
 * os mesmos IDs, o que já deixa o catálogo pronto para relações futuras com mobs,
 * drops, dimensões e botânica.
 */
(function exposeFoodCatalog() {
  const effectDefinitions = {
    speed: {
      name: { pt: "Velocidade", en: "Speed" },
      image: "assets/ui/effects/speed.png",
    },
    strength: {
      name: { pt: "Força", en: "Strength" },
      image: "assets/ui/effects/strength.png",
    },
    "jump-boost": {
      name: { pt: "Super Salto", en: "Jump Boost" },
      image: "assets/ui/effects/jump-boost.png",
    },
    regeneration: {
      name: { pt: "Regeneração", en: "Regeneration" },
      image: "assets/ui/effects/regeneration.png",
    },
    resistance: {
      name: { pt: "Resistência", en: "Resistance" },
      image: "assets/ui/effects/resistance.png",
    },
    "fire-resistance": {
      name: { pt: "Resistência ao Fogo", en: "Fire Resistance" },
      image: "assets/ui/effects/fire-resistance.png",
    },
  };

  const emptyRelations = () => ({
    mobs: [],
    drops: [],
    botany: [],
    dimensions: [],
  });

  const food = (
    nutrition,
    saturationModifier,
    effects = [],
    options = {},
  ) => ({
    nutrition,
    saturationModifier,
    eatTicks: 32,
    eatSpeed: "common",
    effects,
    ...options,
  });

  const item = (
    id,
    namePt,
    nameEn,
    image,
    category,
    foodData = null,
    options = {},
  ) => ({
    id,
    name: { pt: namePt, en: nameEn },
    image,
    category,
    food: foodData,
    catalog: true,
    source: "warspawn",
    relations: emptyRelations(),
    ...options,
  });

  const items = [
    item(
      "rice",
      "Arroz",
      "Rice",
      "assets/items/rice.png",
      "ingredients",
      food(5, 5),
    ),
    item(
      "blt-sandwich",
      "Sanduíche BLT",
      "BLT Sandwich",
      "assets/items/blt-sandwich.png",
      "meals",
      food(12, 10),
    ),
    item(
      "cooked-bacon",
      "Bacon Frito",
      "Cooked Bacon",
      "assets/items/cooked-bacon.png",
      "meals",
      food(14, 15, [
        { id: "strength", level: 1, durationTicks: 2000 },
        { id: "regeneration", level: 1, durationTicks: 2000 },
      ]),
    ),
    item(
      "raw-corn-dog",
      "Corn Dog Cru",
      "Raw Corn Dog",
      "assets/items/raw-corn-dog.png",
      "meals",
      food(4, 1),
    ),
    item(
      "cooked-corn-dog",
      "Corn Dog Frito",
      "Cooked Corn Dog",
      "assets/items/cooked-corn-dog.png",
      "meals",
      food(16, 10),
    ),
    item(
      "cooked-crab-meat",
      "Carne de Caranguejo Cozida",
      "Cooked Crab Meat",
      "assets/items/cooked-crab-meat.png",
      "meals",
      food(6, 3),
    ),
    item(
      "raw-crab-meat",
      "Carne de Caranguejo Crua",
      "Raw Crab Meat",
      "assets/items/raw-crab-meat.png",
      "ingredients",
      food(4, 3),
    ),
    item("cherries", "Cerejas", "Cherries", "assets/items/cherries.png", "ingredients"),
    item(
      "butter-candy",
      "Doce de Manteiga",
      "Butter Candy",
      "assets/items/butter-candy.png",
      "special",
      food(4, 5, [
        { id: "speed", level: 1, durationTicks: 2000 },
        { id: "jump-boost", level: 1, durationTicks: 2000 },
      ]),
    ),
    item(
      "corn",
      "Espiga de Milho",
      "Corn",
      "assets/items/corn.png",
      "ingredients",
      food(6, 5),
    ),
    item(
      "crabby-patty",
      "Hambúrguer de Siri",
      "Crabby Patty",
      "assets/items/crabby-patty.png",
      "meals",
      food(16, 20),
    ),
    item(
      "love",
      "Amor",
      "Love",
      "assets/items/love.png",
      "special",
      food(8, 9.6, [
        { id: "speed", level: 1, durationTicks: 5000 },
        { id: "strength", level: 2, durationTicks: 6000 },
        { id: "jump-boost", level: 1, durationTicks: 5000 },
        { id: "regeneration", level: 3, durationTicks: 6000 },
        { id: "resistance", level: 2, durationTicks: 6000 },
        { id: "fire-resistance", level: 2, durationTicks: 6000 },
      ]),
    ),
    item(
      "butter",
      "Manteiga",
      "Butter",
      "assets/items/butter.png",
      "ingredients",
      food(1, 0.3),
    ),
    item(
      "strawberry",
      "Morango",
      "Strawberry",
      "assets/items/strawberry.png",
      "ingredients",
      food(2, 1),
    ),
    item(
      "cooked-peacock",
      "Pavão Assado",
      "Cooked Peacock",
      "assets/items/cooked-peacock.png",
      "meals",
      food(12, 3),
    ),
    item(
      "raw-peacock",
      "Pavão Cru",
      "Raw Peacock",
      "assets/items/raw-peacock.png",
      "ingredients",
      food(6, 0.3),
    ),
    item(
      "peach",
      "Pêssego",
      "Peach",
      "assets/items/peach.png",
      "ingredients",
      food(4, 0.3),
    ),
    item(
      "spark-fish",
      "Peixe Spark",
      "Spark Fish",
      "assets/items/spark-fish.png",
      "fish",
      food(1, 0.3, [
        { id: "fire-resistance", level: 2, durationTicks: 100 },
      ]),
    ),
    item(
      "blue-fish",
      "Peixe Azul",
      "Blue Fish",
      "assets/items/blue-fish.png",
      "fish",
      food(4, 1),
    ),
    item(
      "gray-fish",
      "Peixe Cinza",
      "Gray Fish",
      "assets/items/gray-fish.png",
      "fish",
      food(5, 0.3),
    ),
    item(
      "fire-fish",
      "Peixe de Fogo",
      "Fire Fish",
      "assets/items/fire-fish.png",
      "fish",
      food(4, 1, [
        { id: "fire-resistance", level: 1, durationTicks: 1200 },
      ]),
    ),
    item(
      "sun-fish",
      "Peixe do Sol",
      "Sun Fish",
      "assets/items/sun-fish.png",
      "fish",
      food(6, 1, [
        { id: "fire-resistance", level: 1, durationTicks: 6000 },
      ]),
    ),
    item(
      "wood-fish",
      "Peixe de Madeira",
      "Wood Fish",
      "assets/items/wood-fish.png",
      "fish",
      food(6, 0.3),
    ),
    item(
      "rock-fish",
      "Peixe de Pedra",
      "Rock Fish",
      "assets/items/rock-fish.png",
      "fish",
      food(3, 0.3),
    ),
    item(
      "pink-fish",
      "Peixe Rosa",
      "Pink Fish",
      "assets/items/pink-fish.png",
      "fish",
      food(4, 1),
    ),
    item(
      "green-fish",
      "Peixe Verde",
      "Green Fish",
      "assets/items/green-fish.png",
      "fish",
      food(3, 1),
    ),
    item(
      "buttered-salted-popcorn",
      "Pipoca com Manteiga e Sal",
      "Buttered & Salted Popcorn",
      "assets/items/buttered-salted-popcorn.png",
      "meals",
      food(3, 7),
    ),
    item(
      "buttered-popcorn",
      "Pipoca com Manteiga",
      "Buttered Popcorn",
      "assets/items/buttered-popcorn.png",
      "meals",
      food(2, 5),
    ),
    item(
      "popcorn",
      "Pipoca",
      "Popcorn",
      "assets/items/popcorn.png",
      "meals",
      food(1, 3),
    ),
    item(
      "cheese",
      "Queijo",
      "Cheese",
      "assets/items/cheese.png",
      "ingredients",
      food(4, 2),
    ),
    item(
      "radish",
      "Rabanete",
      "Radish",
      "assets/items/radish.png",
      "ingredients",
      food(2, 0.3),
    ),
    item(
      "bag-of-popcorn",
      "Saco de Pipoca",
      "Bag of Popcorn",
      "assets/items/bag-of-popcorn.png",
      "meals",
      food(10, 9),
    ),
    item("salt", "Sal", "Salt", "assets/items/salt.png", "ingredients"),
    item(
      "garden-salad",
      "Salada do Jardim",
      "Garden Salad",
      "assets/items/garden-salad.png",
      "meals",
      food(10, 3),
    ),
    item(
      "tomato",
      "Tomate",
      "Tomato",
      "assets/items/tomato.png",
      "ingredients",
      food(4, 0.3),
    ),
    item(
      "raw-bacon",
      "Bacon Cru",
      "Raw Bacon",
      "assets/items/raw-bacon.png",
      "ingredients",
      food(8, 3),
    ),
    item(
      "crystal-apple",
      "Maçã de Cristal",
      "Crystal Apple",
      "assets/items/crystal-apple.png",
      "special",
      food(5, 9.6, [
        { id: "strength", level: 1, durationTicks: 3000 },
        { id: "regeneration", level: 1, durationTicks: 3000 },
      ]),
    ),
    item(
      "pizza",
      "Pizza",
      "Pizza",
      "assets/items/pizza.png",
      "meals",
      food(20, 20, [], { perSlice: true }),
      {
        description: {
          pt: "É posicionada no mundo e consumida por fatias, de forma semelhante ao bolo do Minecraft.",
          en: "Placed in the world and eaten one slice at a time, similarly to Minecraft's cake.",
        },
      },
    ),
    item(
      "quinoa",
      "Quinoa",
      "Quinoa",
      "assets/items/quinoa.png",
      "ingredients",
      food(7, 0.3),
    ),
    item(
      "lava-eel",
      "Enguia de Lava",
      "Lava Eel",
      "assets/items/lava-eel.png",
      "special",
      food(2, 0.3, [
        { id: "fire-resistance", level: 2, durationTicks: 600 },
      ]),
    ),
    item(
      "lettuce",
      "Alface",
      "Lettuce",
      "assets/items/lettuce.png",
      "ingredients",
      food(3, 0.3),
    ),

    /* Ingredientes do Minecraft base usados pelas receitas. */
    item(
      "bread",
      "Pão",
      "Bread",
      "assets/items/bread.png",
      "ingredients",
      null,
      { catalog: false, source: "minecraft" },
    ),
    item(
      "raw-porkchop",
      "Costeleta de Porco Crua",
      "Raw Porkchop",
      "assets/items/raw-porkchop.png",
      "ingredients",
      null,
      { catalog: false, source: "minecraft" },
    ),
    item(
      "raw-chicken",
      "Frango Cru",
      "Raw Chicken",
      "assets/items/raw-chicken.png",
      "ingredients",
      null,
      { catalog: false, source: "minecraft" },
    ),
    item(
      "stick",
      "Graveto",
      "Stick",
      "assets/items/stick.png",
      "ingredients",
      null,
      { catalog: false, source: "minecraft" },
    ),
    item(
      "sugar",
      "Açúcar",
      "Sugar",
      "assets/items/sugar.png",
      "ingredients",
      null,
      { catalog: false, source: "minecraft" },
    ),
    item(
      "milk-bucket",
      "Balde de Leite",
      "Milk Bucket",
      "assets/items/milk-bucket.png",
      "ingredients",
      null,
      { catalog: false, source: "minecraft" },
    ),
    item(
      "paper",
      "Papel",
      "Paper",
      "assets/items/paper.png",
      "ingredients",
      null,
      { catalog: false, source: "minecraft" },
    ),
    item(
      "carrot",
      "Cenoura",
      "Carrot",
      "assets/items/carrot.png",
      "ingredients",
      null,
      { catalog: false, source: "minecraft" },
    ),
    item(
      "bowl",
      "Tigela",
      "Bowl",
      "assets/items/bowl.png",
      "ingredients",
      null,
      { catalog: false, source: "minecraft" },
    ),
  ];

  /*
   * Ordem da aba "Consumíveis" do mod, reconstruída da esquerda para a direita
   * e de cima para baixo. O sal não aparece na captura da aba criativa, então
   * permanece ao final para continuar acessível no catálogo e nas receitas.
   */
  const creativeOrder = [
    "crystal-apple",
    "love",
    "butter-candy",
    "lava-eel",
    "sun-fish",
    "fire-fish",
    "wood-fish",
    "rock-fish",
    "gray-fish",
    "pink-fish",
    "blue-fish",
    "green-fish",
    "spark-fish",
    "lettuce",
    "tomato",
    "radish",
    "cherries",
    "strawberry",
    "peach",
    "rice",
    "quinoa",
    "raw-peacock",
    "cooked-peacock",
    "raw-bacon",
    "cooked-bacon",
    "raw-crab-meat",
    "cooked-crab-meat",
    "raw-corn-dog",
    "cooked-corn-dog",
    "garden-salad",
    "blt-sandwich",
    "crabby-patty",
    "corn",
    "popcorn",
    "buttered-popcorn",
    "buttered-salted-popcorn",
    "bag-of-popcorn",
    "butter",
    "cheese",
    "pizza",
    "salt",
  ];

  const recipes = [
    {
      id: "blt-sandwich",
      station: "crafting",
      type: "shapeless",
      grid: [
        "cooked-bacon", "lettuce", "tomato",
        "butter", "bread", null,
        null, null, null,
      ],
      result: { item: "blt-sandwich", count: 1 },
    },
    {
      id: "raw-bacon",
      station: "crafting",
      type: "shapeless",
      grid: [
        "raw-porkchop", "salt", null,
        null, null, null,
        null, null, null,
      ],
      result: { item: "raw-bacon", count: 2 },
    },
    {
      id: "cooked-bacon",
      station: "furnace",
      type: "smelting",
      ingredient: "raw-bacon",
      result: { item: "cooked-bacon", count: 1 },
      timeTicks: 200,
      experience: 1,
    },
    {
      id: "cooked-corn-dog",
      station: "furnace",
      type: "smelting",
      ingredient: "raw-corn-dog",
      result: { item: "cooked-corn-dog", count: 1 },
      timeTicks: 200,
      experience: 1,
    },
    {
      id: "raw-corn-dog",
      station: "crafting",
      type: "shaped",
      grid: [
        "corn", "raw-chicken", null,
        "raw-porkchop", "stick", null,
        null, null, null,
      ],
      result: { item: "raw-corn-dog", count: 4 },
    },
    {
      id: "cooked-crab-meat",
      station: "furnace",
      type: "smelting",
      ingredient: "raw-crab-meat",
      result: { item: "cooked-crab-meat", count: 1 },
      timeTicks: 200,
      experience: 1,
    },
    {
      id: "butter-candy",
      station: "crafting",
      type: "shapeless",
      grid: [
        "butter", "sugar", null,
        null, null, null,
        null, null, null,
      ],
      result: { item: "butter-candy", count: 1 },
    },
    {
      id: "crabby-patty",
      station: "crafting",
      type: "shapeless",
      grid: [
        "cooked-crab-meat", "lettuce", null,
        "tomato", "bread", null,
        null, null, null,
      ],
      result: { item: "crabby-patty", count: 1 },
    },
    {
      id: "butter",
      station: "crafting",
      type: "shapeless",
      grid: [
        "milk-bucket", "milk-bucket", null,
        null, null, null,
        null, null, null,
      ],
      result: { item: "butter", count: 4 },
    },
    {
      id: "cooked-peacock",
      station: "furnace",
      type: "smelting",
      ingredient: "raw-peacock",
      result: { item: "cooked-peacock", count: 1 },
      timeTicks: 200,
      experience: 1,
    },
    {
      id: "popcorn",
      station: "furnace",
      type: "smelting",
      ingredient: "corn",
      result: { item: "popcorn", count: 1 },
      timeTicks: 200,
      experience: 1,
    },
    {
      id: "buttered-popcorn",
      station: "crafting",
      type: "shapeless",
      grid: [
        "popcorn", "butter", null,
        null, null, null,
        null, null, null,
      ],
      result: { item: "buttered-popcorn", count: 1 },
    },
    {
      id: "buttered-salted-popcorn-a",
      station: "crafting",
      type: "shapeless",
      grid: [
        "popcorn", "salt", null,
        "butter", null, null,
        null, null, null,
      ],
      result: { item: "buttered-salted-popcorn", count: 1 },
    },
    {
      id: "buttered-salted-popcorn-b",
      station: "crafting",
      type: "shapeless",
      grid: [
        "buttered-popcorn", "salt", null,
        null, null, null,
        null, null, null,
      ],
      result: { item: "buttered-salted-popcorn", count: 1 },
    },
    {
      id: "pizza",
      station: "crafting",
      type: "shapeless",
      grid: [
        "tomato", "cheese", null,
        "cooked-bacon", "bread", null,
        null, null, null,
      ],
      result: { item: "pizza", count: 1 },
    },
    {
      id: "cheese",
      station: "crafting",
      type: "shapeless",
      grid: [
        "milk-bucket", "milk-bucket", null,
        "milk-bucket", "milk-bucket", null,
        null, null, null,
      ],
      result: { item: "cheese", count: 8 },
    },
    {
      id: "bag-of-popcorn",
      station: "crafting",
      type: "shaped",
      grid: [
        "popcorn", "popcorn", "paper",
        "popcorn", "popcorn", "paper",
        "popcorn", "popcorn", "paper",
      ],
      result: { item: "bag-of-popcorn", count: 1 },
    },
    {
      id: "garden-salad",
      station: "crafting",
      type: "shapeless",
      grid: [
        "lettuce", "tomato", "radish",
        "carrot", "bowl", null,
        null, null, null,
      ],
      result: { item: "garden-salad", count: 1 },
    },
  ];

  window.WarSpawnCatalog = Object.freeze({
    effects: effectDefinitions,
    items,
    recipes,
    creativeOrder,
  });
})();
